%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
RGBCamera:
  width: 640
  height: 480
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  bits: 8

DepthCamera:
  depth_scale: 5000.0
  max_range: 5.0

TSDF:
  voxel_size: 0.01
  block_resolution: 16
  est_block_count: 50000
  out_dir: "results"

MaskRCNN:
  score_threshold: 0.95
