%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
RGBCamera:
  type: "PinHole"
  width: 640
  height: 480
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  bits: 8

DepthCamera:
  depth_scale: 5000.0
  max_range: 5.0
  bits: 16

TSDF:
  voxel_size: 0.005
  sdf_trunc: 0.05
  space_carving: True
  out_dir: "results"
  apply_pose: True
  preprocess: True

MaskRCNN:
  score_threshold: 0.95
